code --install-extension EditorConfig.EditorConfig
code --install-extension wesbos.theme-cobalt2
code --install-extension johnpapa.angular2
code --install-extension hookyqr.beautify
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PeterJausovec.vscode-docker
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension pkief.material-icon-theme
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cssho.vscode-svgviewer
code --install-extension esbenp.prettier-vscode
code --install-extension eg2.tslint
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension jeremyljackson.vs-docblock
code --install-extension dbaeumer.vscode-eslint
code --install-extension hoovercj.vscode-power-mode
code --install-extension joelday.docthis
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension octref.vetur
code --install-extension pnp.polacode
code --install-extension shinnn.stylelint
code --install-extension tinaciousdesign.theme-tinaciousdesign
code --install-extension waderyan.gitblame
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension mrmlnc.vscode-scss
code --install-extension anseki.vscode-color
code --install-extension felipecaputo.git-project-manager
code --install-extension gruntfuggly.todo-tree
code --install-extension nrwl.angular-console
